name = "Testing 3.1 Power Machines Basic"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ae19f1456c26c6ab53b4186cd8f6a31bb00b4d7aa935f933209507b762dfc6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
