name = "Testing 3.1 Power Machines Basic"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23471ab2c2c18ccf472b8f3a111074580a20ebddb6583b84e61d6242c113e7d0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
