name = "Testing 3.1 Power Machines Basic"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9e7d07686830aec20a1f42f94e871020c931dfa5071660e78e923c25b12e18e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
