name = "Testing 3.1 Power Machines Basic"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de7149d3de4bcd98dd9bb138e28865de666749f948b847c43ca613b34dd3b98"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
